{{- if and .Values.kepler.enabled .Values.kepler.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kepler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kepler
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kepler
  endpoints:
  - port: http
    interval: 30s
{{- end }}
