{{- if .Values.storage.minio.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: default
spec:
  encryptedData:
    rootPassword: AgCsbprDkeLJpwq9aGUCvaImamp2OBI5KFmjiMt3CfkvoewUHgRZk3IU7VYwCapryEWE6P8yfg/yyRa3kEUKQLfwMBVnoUil4jayQSvpuuZ9n+ntE8hLCEILqHQ106Zt1mNamzD2315XGPybB9JRW3b5L3MmjOlPIB8QdwCm4HCEB7Tio8WHdlPLq/qUH3szbz3KZB8RxsIBWyOSjk0et6xXDaXMcf5ScjUt4jkmsb/S8UnSpluls07t4HqhuK93AG2vAlV5VxMd5o5uwREFzWa8JW50/b/CcHQO+JnVM54iXDavSqA67FS9PaW3aYC9KmQSvtHaLSMaoQwpLdBNqW+v1v1+4SqiCZ+r/RnZJ51o41zlyxO1kLIlyBWth3lCvMQbUZX36uLTZovyNkY9CNNVUHsXaUX4pYmkDgSace4j1ai3eDyYQa/seHZom8AZWB61iBC60frZmM5vMUcyAjy5QKiJ/i4fqHA5dng48QKBMI0F6rmgWGc1tWxpaTgeSK+MUI46GO8xo/KmSrlXMKRHSSQfDg2C+//fplmtYuqCZNhX3eydjOqczE9vCQAz/B921KbqqxEdgOP5nNwXcDcwnOJ9mGevluTrdziDRx3NvdwXBzpEb+2C98wVqi8ukK5oST2eIsoCJbhThhox9hvrk6YkRP1enPo0Xe3AQFqUSsDLMJw0SUOQOgxTrtXSmtJd+TTPKy24cy+pzL4hUyR2zQ/qPrmsRz3Jhf9kQ29HpQ==
    rootUser: AgBwnZXWm4M5P/FTvIGKV/TPQTT+NF8l0bcloNJVokL2FTImpW4QC7cRH3OA/Cc4kRz7P9ZaBFSRwrUguGDxcMED0fn4s7pDcQHeQgsmLOTgHUi/ReJAesH/42p6DOAvQMtH+P5z+Zds3DIzHy1NIVtJ1cfWFjZ55V+Ym5kFobF5OkRyCzMAUy6DUpahADsKtK7E34ulfn52PyUKKVA7vkBvhU90VxY+T2CdN5QNlUjz2kRvYPQyG7waOtyscsGBFKO+hENcHEc+9kEGN0euC2CYqe3Xzq9pXan/LfdtYwdTFXHbQgBUhL5N0TnhTlFMu5YLCScQStm3Ygt9kbIboTUpq7hSa6x0znZRP7V780YVWHJG4yqyo4n1f/9hF9QmBWrjiTR5qp48ujGjndvb9gv9TeYmlNpplLiS+8M6R64reXNxNN4vyyOQZl7AxyC+OTj+hhEFWKgwM1pNxpzAvKQxO9vfFQsr7vsz8HQB0h6EqqRrqQHShLZPRHrKSjy3R8gi6BXn7QvNOazWixVR409XvoBpQ5ZePZWaemiTg7BvLOKliNLGiNfuYJAMRJmpMzJ5tEFG2pDrQfHN2yts1CaRVbWGvDYXXU9F6w6XNLrVaMtdVLYIVcUIrLH9S+ykfbly3PMw5A/3i02JBmincktI8PBdQacQMUW40Uk0MXTmdf1f/plcy01+4La9u36HGORZWiKKIw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: default
---
{{- end }}
