apiVersion: v2
name: cluster-config
description: Umbrella chart para centralizar configurações dinâmicas do cluster
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kepler
    version: "0.5.11" # Latest stable as of Nov 2025
    repository: "https://sustainable-computing-io.github.io/kepler-helm-chart"
    condition: kepler.enabled

  - name: keda
    version: "2.18.1"
    repository: "https://kedacore.github.io/charts"
    condition: keda.enabled

  - name: kube-prometheus-stack
    version: "66.3.0" # Using a stable version (approx Nov 2024) to be safe, or 66.x
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: minio
    version: "5.4.0" # Official MinIO Chart
    repository: "https://charts.min.io/"
    condition: storage.minio.enabled