apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgCaw2kKfJfxy6eBPaxPXFV7ESE13nxYqCi4WJFpCn195iCPy2HPJ3ISssbwJ8BqSMQrBHsJ68XHq77dLIeg8zulZJ9r6ViPLq4XuuhfVumCMPv86im1idQEUDL+U7ObzgqsighALngX3F3n0FXP6ZQMozZYu8ojFceLdBqJkX06t7tKd+qZ0QenMGGAb5LYmPOWKdPevlW0Q718zuViDQDJyBlQ4Ji3ZvZXBj9oTwWPcDNXTAk++tkqiVLRxlqJJDktE5vdvaVGASa7mkhV0RPfnvDdUvu27e/83Z3pdtwgxo/R8aeL++jKjusTDHtb12E3SkivUxRKr8GU6SniFBXxaDXAqnBP/Ja6p82NGTDxpxsBdHFv+cV3tRAc3lCgluD//dq3BuZEAR2UsJ5ATOGKa8u08kSziX4gbl0kQlsMBhkY5fMUf1Ld8httuOdc4Rmk5WKO7xhlodneIFYQpRQuKpY2wN0xAcZqr7ZHlAgb4ni/5uUIKh72Tnlq+JISyzQ/ebrKjmgawJUuUp07uhjo+H+Bo+xZ6Vk06/1YXsK2dXHMZwhD1OJj8KgzPQvMFzIjf37feWeQTOAvu1bmZ4+Ac6/g6FhHnPSLuArxSCRzL442aeeNjfzz1W93v75/SfVUE+QqiPhT9DWeBhZyE++usW8WPxNvE9rH/t6zvccqI397CcQMwWhSdQhfttG7FbvA0od4frveFXjcwTL4NSA7U9FUF54SY57UrWl2axhfmtifH/fKOnR2
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo-events
---
